# Netlify configuration for a static landing page
# This configuration explicitly avoids running any build commands.

[build]
  # IMPORTANT: Set this to the directory containing your index.html and Assets folder.
  # If index.html is at the root of your repo, use "."
  # If it's in a folder named "public", use "public", etc.
  publish = "." # <--- CHANGE THIS if your site files are not at the root

  # Explicitly tell Netlify NOT to run any build command.
  # This prevents it from trying to detect/build Python, Node, etc.
  command = ""
  ignore = "*.py"

# This rule ensures that requests to paths that don't match a file
# (like mysite.com/some-path) still serve your main index.html.
# Useful for single-page apps, but generally harmless for a simple landing page.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build environment settings are not strictly needed since no build command runs,
# but leaving NODE_VERSION doesn't hurt. You could remove this section.
# [build.environment]
#   NODE_VERSION = "18" # Not used if command = ""

# Security headers are generally good practice for any website.
# These settings help protect against common web vulnerabilities.
# They don't interfere with serving static files or ignoring Python.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Adjusted CSP slightly for clarity, but functionally similar to yours
    # Allows resources from self, inline styles/scripts, data URIs for images,
    # and external resources (like CDNs for fonts/css) over HTTPS.
    Content-Security-Policy = "default-src 'self' https: data:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https:; img-src 'self' data: https:;"

