# Netlify configuration for a static landing page
# This configuration explicitly avoids running any build commands.

[build]
  # IMPORTANT: This points to the directory containing your index.html, Assets, and dist folders.
  # This matches your structure where index.html is in _wwwroot.
  publish = "_wwwroot"

  # Explicitly tell Netlify NOT to run any build command.
  # Perfect for pre-built static sites.
  command = ""
  # Optional: Ignore specific files during build checks (less relevant with command="")
  # ignore = "*.py"

# This rule ensures that requests to paths that don't match a file
# still serve your main index.html. Generally good practice.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers are good practice. These look fine.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Allows resources from self, inline styles/scripts, data URIs, and external HTTPS (CDNs, etc.)
    Content-Security-Policy = "default-src 'self' https: data:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https:; img-src 'self' data: https:;"

