name: CI Pipeline

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run flake8 linter
        run: flake8 src/ tests/

      - name: Run black formatter
        run: black --check src/ tests/

      - name: Run unit tests
        run: pytest tests/ -v
